// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Portolan contributors

package graph

import (
	"cmp"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"
	"time"
)

// prepared is the audit after folding, joining, grouping and ranking — the
// single shaping pipeline that BOTH the brief and the findings sidecar read.
//
// They must not each do their own: an ID derived from a differently-shaped
// finding names something the reader cannot see, and a suppression keyed on it
// would silence the wrong row.
type prepared struct {
	audit        *Audit
	x            *crossRef
	drops        []DropEdge
	groups       []halfOpenGroup
	deadExpected []deadRefGroup
	deadReview   []deadRefGroup
}

func prepare(g *Graph, a *Audit) prepared {
	// Fold ephemeral ports BEFORE cross-referencing, so a dynamically-allocated
	// port is compared as "ephemeral" rather than as a number that will never be
	// seen again. Everything downstream — the join, the ranking, the rendering,
	// the IDs — then sees one stable row per standing problem instead of a new
	// one daily.
	folded := &Audit{
		HalfOpen:       a.HalfOpen,
		NoDefaultDeny:  a.NoDefaultDeny,
		WorldReachable: a.WorldReachable,
		DeadRefs:       a.DeadRefs,
		Drops:          foldEphemeral(a.Drops),
	}
	x := newCrossRef(folded)
	folded.Drops = rankDrops(folded.Drops, x, g.Flows)
	expected, review := groupDeadRefs(folded.DeadRefs)
	return prepared{
		audit:        folded,
		x:            x,
		drops:        folded.Drops,
		groups:       rankHalfOpen(groupHalfOpen(folded.HalfOpen), x),
		deadExpected: expected,
		deadReview:   review,
	}
}

// BriefOptions carries what a brief needs to have a MEMORY: what it said last
// time, and which decisions have already been made.
type BriefOptions struct {
	// Previous is the last run's findings. Without it every finding is NEW
	// forever and a fix is invisible — you change a policy, the finding stops
	// appearing, and nothing anywhere tells you it was you.
	Previous *FindingSet
	// Suppressions maps finding ID → why. Suppressed findings are withheld from
	// the body and counted at the end: a decision, once made, should not be
	// re-argued every morning.
	Suppressions map[string]string
}

// Brief renders audit findings as a Markdown investigation brief for an LLM
// agent (or a human) with read access to the cluster. It hands over hypotheses,
// evidence and verification commands — never conclusions: those belong to the
// investigator after checking live state. This form has no memory.
func Brief(g *Graph, a *Audit) []byte { return BriefWith(g, a, BriefOptions{}) }

// BriefWith renders the brief with a memory: diffed against a previous run, and
// filtered by decisions already taken.
func BriefWith(g *Graph, a *Audit, opts BriefOptions) []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p := prepare(g, a)
	a, x := p.audit, p.x

	// Memory: what is new since last time, what has stuck around, what is gone.
	cur := ComputeFindings(g, a)
	resolved := Diff(cur, opts.Previous)
	status := map[string]string{}
	for _, f := range cur.Findings {
		status[f.ID] = f.Status
	}
	suppressed := 0
	hidden := func(id string) bool {
		if _, ok := opts.Suppressions[id]; ok {
			suppressed++
			return true
		}
		return false
	}
	mark := func(id string) string {
		if opts.Previous == nil {
			return "" // nothing to compare against; do not shout NEW at everything
		}
		if status[id] == "NEW" {
			return " · **NEW**"
		}
		return ""
	}

	w("# Portolan investigation brief\n\n")
	if g.Cluster != "" {
		w("Cluster: **%s** · ", g.Cluster)
	}
	w("generated by %s\n\n", g.Tool)
	w("Topology at capture: %d namespaces, %d workloads, %d policies, %d declared allow-edges.\n\n",
		g.Stats.Namespaces, g.Stats.Workloads, g.Stats.Policies, g.Stats.Edges)

	// Two clocks, said out loud.
	//
	// Policy is SAMPLED (a snapshot, every collection cycle); traffic is
	// STREAMED (continuous, and re-read the moment this brief is generated). So
	// the traffic timestamps legitimately run minutes fresher than the policy
	// one — and printing a single undated "snapshot taken" line above drops
	// last-seen AFTER it made the brief look broken. Two clocks are correct; two
	// unlabelled clocks are a bug.
	w("- **Policy** sampled at `%s` — a point-in-time read of the cluster's declared topology.\n", g.TakenAt)
	if f := g.Flows; f != nil && f.Status == "ok" && !f.To.IsZero() {
		w("- **Traffic** observed through `%s` — streamed continuously, so it runs fresher than the "+
			"policy above. Drop timestamps later than the policy sample are expected, not errors.\n",
			f.To.Format(time.RFC3339))
	}
	w("\n")

	// Observation provenance — the most important paragraph in the brief for
	// anyone about to reason from an ABSENCE.
	//
	// "No drops on this edge" is worth almost nothing from a 2%-covered sample
	// and quite a lot from a 99%-covered one, and a reader (human or model)
	// cannot tell those apart unless we say which they are holding. A brief
	// pasted into a chatbot is exactly where that mistake gets made
	// confidently, at length, and with citations.
	if f := g.Flows; f != nil && f.Status == "ok" {
		cov := int(f.Coverage*100 + 0.5)
		w("Observed traffic: **%s** window, **%d%% covered** — %s of it actually watched (source: `%s`).\n\n",
			f.Window, cov, f.Watched, f.Source)
		switch {
		case f.Source == "buffer":
			w("> **Read this before drawing any conclusion from an absence.** These observations are a " +
				"single read of Hubble's event buffer, which is bounded by *capacity*, not time — on a busy " +
				"cluster it holds seconds no matter how long a window was asked for. Traffic missing from " +
				"this brief was almost certainly **not observed**, rather than absent. Do not conclude that " +
				"an edge is unused, and do not propose removing a rule on that basis.\n\n")
		case cov < 80:
			w("> **Read this before drawing any conclusion from an absence.** Only %d%% of this window was "+
				"actually watched, so traffic that does not appear here may simply have gone unseen. "+
				"Traffic that *is* listed is solid evidence; its absence is not.\n\n", cov)
		default:
			w("Coverage is high, so absence is meaningful here: an edge with no observed traffic in this " +
				"window genuinely carried none. That is evidence a rule may be unused — still verify before " +
				"proposing removal.\n\n")
		}
	} else if g.Flows == nil {
		w("> **No traffic observation in this brief.** Every finding below is derived from *declared " +
			"policy topology alone*. Nothing here tells you what actually flowed, so no finding can be " +
			"confirmed or dismissed from this document by itself.\n\n")
	}

	w(`## Instructions for the investigating agent

These findings come from **declared policy topology only** (visualization-grade
selector matching). They are hypotheses, not verdicts. For each finding:

1. Work **one finding at a time**. Verify against live cluster state before
   concluding anything — never diagnose from this brief alone.
2. Use **read-only commands first** (kubectl get/describe, hubble observe).
   Propose fixes as GitOps-reviewable YAML; do not apply changes directly
   unless your operator explicitly asks.
3. Classify each finding when done, with the evidence that decided it:
   - **BENIGN** — intentional or explained (completed Job, scaled-down or
     powered-off node, deliberate one-way allow, traffic that never flows)
   - **CONFIRMED** — a real gap or dead rule, with the proposed fix
   - **INCONCLUSIVE** — say exactly what evidence is missing
4. If Hubble is available, prefer flow evidence over reasoning about specs.

`)

	// Resolved first, and unprompted.
	//
	// This is the only part of the brief that says you WON. Everything else is a
	// list of things wrong with your cluster, and a tool whose list only ever
	// grows teaches you to stop reading it. A finding that has gone away is the
	// receipt for work already done.
	if len(resolved) > 0 {
		w("## ✅ Resolved since the last run (%d)\n\n", len(resolved))
		w("These were findings last time and are not findings now. Nothing to do — this is the " +
			"record that something got fixed.\n\n")
		for _, f := range resolved {
			w("- `%s` — %s\n", f.Kind, f.Title)
		}
		w("\n")
	}

	n := 0
	if len(a.Drops) > 0 {
		n++
		w("## Finding %d — traffic drops observed in the capture window (%d)\n\n", n, len(a.Drops))
		w("These are not topology inferences: the datapath **actually denied** this traffic "+
			"during the %s window ending %s. Strongest evidence in this brief — a drop that was "+
			"seen, happened, whatever the coverage was.\n\n",
			g.Flows.Window, g.Flows.To.Format(time.RFC3339))

		// Counts are raw totals over the time actually watched, so they scale
		// with coverage: the SAME cluster, sampled at 50% and at 98%, yields
		// counts that differ ~2x while nothing changed. That is the single most
		// misleading thing a reader can do with this section — it turns steady
		// background noise into "the cluster is degrading". So print the rate
		// beside the count, and say plainly which one to compare.
		rate, rated := ratePerHour(g.Flows)
		if rated {
			w("Counts are raw totals over the %s actually watched. To compare with another run — a "+
				"different day, a different coverage — use the **per-hour rate**, not the count: the "+
				"count scales with how long we were looking, the rate does not.\n\n", g.Flows.Watched)
		}
		for _, d := range a.Drops {
			id := findingID("drop", d.Src, d.Dst, d.Port, d.Reason)
			if hidden(id) {
				continue
			}
			key := d.Src + "|" + d.Dst + "|" + d.Port
			var tag string
			switch {
			case x.confirmed[key]:
				tag = " · **CONFIRMED** — a half-open finding declares this exact pair and port"
			case x.mismatch[key] != nil:
				tag = " · ⚠ **PORT MISMATCH** — policy declares " +
					"`" + strings.Join(x.mismatch[key], "`, `") + "` for this pair, not this port"
			}
			w("- `%s → %s` %s — **%s** ×%d%s, last seen %s%s%s%s\n",
				d.Src, d.Dst, d.Port, d.Reason, d.Count, rate(d.Count),
				d.LastSeen.Format(time.RFC3339), activity(d, g.Flows), tag, mark(id))
		}

		// The cross-reference, done HERE rather than asked of the reader. The
		// old instruction — "a half-open naming the same pair confirms it" —
		// ignores the port, and on this cluster that produced a fix that would
		// not have worked. See crossRef.
		if len(x.mismatch) > 0 {
			w("\n### ⚠ Denied on a port no policy declares\n\n")
			w("The pairs below are being denied on a port that **none of their policies mention**. " +
				"Each also has a half-open finding further down, on a DIFFERENT port — so the obvious " +
				"move, opening the port the policy names, would leave these drops exactly where they " +
				"are. Do not follow that half-open's suggested fix for this traffic. Establish what is " +
				"really talking on the dropped port first; a dynamic or ephemeral port usually means " +
				"the policy is written against the wrong port in the first place.\n\n")
			for _, d := range a.Drops {
				ports, ok := x.mismatch[d.Src+"|"+d.Dst+"|"+d.Port]
				if !ok {
					continue
				}
				w("- `%s → %s` — **denied on %s**, but policy only declares %s\n",
					d.Src, d.Dst, d.Port, "`"+strings.Join(ports, "`, `")+"`")
			}
			w("\n")
		}

		w("\nTriage:\n\n" +
			"- **`POLICY_DENIED` between two cluster workloads, on a port a half-open finding also " +
			"declares** → confirmed misconfiguration. Topology predicted it and the datapath did it; " +
			"nothing in this brief is stronger. Those drops are marked below.\n" +
			"- **`POLICY_DENIED` on a port no policy declares** → see the section above. The pair " +
			"matching is NOT enough; the port has to match too.\n" +
			"- **`POLICY_DENIED` to or from `entity:world`** → usually correct enforcement doing its " +
			"job. Verify the exposure is meant to be closed rather than rushing to open it.\n" +
			"- **Other reasons** (`VLAN_FILTERED`, `CT_MAP_INSERTION_FAILED`) are datapath conditions, " +
			"not policy — investigate separately.\n" +
			"- **A drop marked `stopped`** already ended. Do not open a rule for traffic that is no " +
			"longer being attempted; find out what changed instead.\n" +
			"\n```sh\n# Watch the pair live:\nhubble observe --verdict DROPPED " +
			"--from-namespace <src-ns> --to-namespace <dst-ns> --since 1h -o compact\n```\n\n")
	}
	// Half-open passages, GROUPED.
	//
	// One policy allowing keycloak out to kube-system on 53/UDP produced nine
	// findings — one per pod that happens to live in kube-system — each with the
	// same policy, the same port, the same diagnosis and the same nine-line
	// verify recipe. Longhorn produced three. That is one fact stated sixteen
	// times, and a brief that repeats itself is a brief that gets skimmed.
	//
	// The fact is (policy, ports, source namespace → destination namespace). The
	// peers are a detail of it, so they go inside.
	groups := p.groups
	if len(groups) > 0 {
		// The recipe is the same shape for every one of them, so it is stated
		// ONCE, parameterised — not pasted into each finding.
		w("## Half-open passages (%d)\n\n", len(groups))
		w("Egress declared per-peer, into a default-deny namespace that never declares the matching " +
			"ingress. If the traffic is ever sent it is allowed out and dropped on arrival.\n\n")
		w("**How to verify any of them** (substitute from the finding):\n\n```sh\n" +
			"# 1. Is this path actually attempted? Drops here confirm a real gap:\n" +
			"hubble observe --from-namespace <SRC-NS> --to-namespace <DST-NS> --verdict DROPPED --since 1h -o compact\n" +
			"# 2. What does the declaring policy actually say?\n" +
			"kubectl get <KIND> -n <POLICY-NS> <POLICY> -o yaml\n" +
			"# 3. What does the receiving namespace currently accept?\n" +
			"kubectl get cnp,netpol -n <DST-NS> -o yaml | grep -B3 -A15 ingress\n```\n\n")
		w("**How to read the outcome.** Drops observed **on the declared port** → missing ingress " +
			"allow, propose one. Drops on any *other* port → a different problem entirely, and opening " +
			"the declared port will not touch it.\n\n")
		w("Nothing observed is the case to be careful with. It means one of two very different " +
			"things, and only one of them is \"delete the rule\":\n\n" +
			"- The rule **reaches nobody** in that namespace → genuinely dead; verify and remove.\n" +
			"- The rule **reaches someone else fine**, and these peers are collateral from a " +
			"namespace-wide selector → the rule is **live**. Removing it breaks the working path. " +
			"Narrow the selector, or suppress the finding.\n\n" +
			"Each finding below says which. Do not infer it from the silence alone.\n\n")
	}
	for _, gr := range groups {
		id := findingID("half-open", strings.Join(gr.Policies, ","),
			strings.Join(gr.Ports, ","), gr.SrcNS, gr.DstNS)
		if hidden(id) {
			continue
		}
		n++
		w("### Finding %d — `%s` → `%s` on %s%s\n\n", n, gr.SrcNS, gr.DstNS,
			strings.Join(gr.Ports, ", "), mark(id))
		w("Declared by %s. `id: %s`\n\n", "`"+strings.Join(gr.Policies, "`, `")+"`", id)

		if len(gr.Srcs) == 1 {
			w("**Sender:** `%s`\n\n", gr.Srcs[0])
		} else {
			w("**Senders (%d):** `%s`\n\n", len(gr.Srcs), strings.Join(gr.Srcs, "`, `"))
		}
		if len(gr.Dsts) == 1 {
			w("**Unreachable peer:** `%s`\n\n", gr.Dsts[0])
		} else {
			w("**Unreachable peers (%d)** — the policy names the namespace, so it fans out to every "+
				"workload in it:\n\n", len(gr.Dsts))
			for _, d := range gr.Dsts {
				w("- `%s`\n", d)
			}
			w("\n")
		}

		// What was ACTUALLY denied on this pair, cross-referenced by PORT. The
		// three answers demand three different responses, and the brief used to
		// give the same one to all three.
		hit, other := x.forGroup(gr)
		switch {
		case len(hit) > 0:
			w("**Observed:** genuinely being denied, on `%s` — the port this policy declares. "+
				"Topology predicted it and the datapath did it. This one is real.\n\n",
				strings.Join(hit, "`, `"))
		case len(other) > 0:
			w("**⚠ Observed, but NOT on this port.** This pair is being denied on `%s` — not on `%s`, "+
				"which is what the policy declares. **The fix above does not apply to that traffic**: "+
				"opening `%s` would leave those drops exactly where they are. Two different things are "+
				"happening here and only one of them is this finding. Work out what is really talking on "+
				"`%s` first — a dynamic or ephemeral port usually means the policy names the wrong port.\n\n",
				strings.Join(other, "`, `"), strings.Join(gr.Ports, "`, `"),
				strings.Join(gr.Ports, "`, `"), strings.Join(other, "`, `"))
		default:
			// Nothing observed on the half-open peers. Before calling the rule
			// dead — which would have someone DELETE it — ask whether the same
			// rule is reaching anyone successfully. If it is, it is not dead; it
			// is alive and merely too loose, and removing it breaks the live path.
			sibs, carrying := workingSiblings(g, gr)
			switch {
			case len(sibs) > 0:
				w("**⚠ This rule is NOT dead — it is too loose.** The same rule reaches `%s` in `%s` "+
					"successfully%s. Its selector names the *namespace*, so it also matches the %d peer(s) "+
					"above, which declare no ingress and were never going to receive this traffic. Their "+
					"silence is the selector fanning out, not a rule nobody uses.\n\n",
					strings.Join(sibs, "`, `"), gr.DstNS,
					map[bool]string{true: " — and traffic was observed flowing on it in this very window", false: ""}[carrying],
					len(gr.Dsts))
				w("**Do not propose removing this rule.** Deleting it would cut the working passage " +
					"above. If the noise bothers you, narrow the selector to the peers that actually " +
					"serve this traffic; otherwise this finding is benign and worth suppressing.\n\n")
			case g.Flows != nil && g.Flows.Status == "ok" && g.Flows.Coverage >= 0.8:
				w("**Observed:** nothing, and this rule reaches nobody in `%s` successfully either. "+
					"Across %s of watched traffic (%.0f%% coverage) the passage was never attempted. At "+
					"this coverage that is real evidence the rule is dead rather than broken — verify "+
					"that the peer truly no longer exists, then propose removing it.\n\n",
					gr.DstNS, g.Flows.Watched, g.Flows.Coverage*100)
			}
		}

		var cmds []string
		for _, p := range gr.Policies {
			if c := policyGetCmd(p); c != "" {
				cmds = append(cmds, c)
			}
		}
		if len(cmds) > 0 {
			w("```sh\n%s\nhubble observe --from-namespace %s --to-namespace %s --verdict DROPPED --since 1h -o compact\n```\n\n",
				strings.Join(cmds, "\n"), gr.SrcNS, gr.DstNS)
		}
	}

	if len(a.NoDefaultDeny) > 0 {
		n++
		w("## Finding %d — namespaces with workloads but no default-deny\n\n", n)
		for _, ns := range a.NoDefaultDeny {
			w("- `%s`\n", ns)
		}
		w("\nEvery workload in these namespaces is default-allow in the unpolicied direction(s). " +
			"Verify whether that is intentional; if not, propose the cluster's standard default-deny " +
			"policy for each.\n\n```sh\nkubectl get cnp,ccnp,netpol -n <namespace>\n```\n\n")
	}

	if len(a.WorldReachable) > 0 {
		n++
		w("## Finding %d — workloads with declared ingress from world/all\n\n", n)
		for _, wl := range a.WorldReachable {
			w("- `%s`\n", wl)
		}
		w("\nUsually intentional (ingress controllers, LoadBalancer services, VPN gateways). " +
			"Confirm each is a deliberate exposure path and is fronted by the expected protections; " +
			"flag anything that should not be internet-facing.\n\n")
	}

	if len(a.DeadRefs) > 0 {
		n++
		expected, review := p.deadExpected, p.deadReview
		w("## Finding %d — selector references matching no live workload (%d selectors)\n\n",
			n, len(expected)+len(review))
		w("Grouped by SELECTOR, not by policy: `pgbouncer-db-init` appearing in fourteen namespaces is " +
			"one fact about one kind of Job, not fourteen findings. The policies referencing each are " +
			"listed under it.\n\n")

		if len(expected) > 0 {
			w("### Expected — run-to-completion workloads (%d)\n\n", len(expected))
			w("These name Jobs, init containers and bootstrap tasks: pods that exist only while they " +
				"run, so matching nothing at rest is *correct*. Removing these rules would break the next " +
				"run. Skim, confirm the naming really is job-like, and move on — they are listed to be " +
				"dismissed, not investigated.\n\n")
			for _, r := range expected {
				id := findingID("dead-selector", r.Selector)
				if hidden(id) {
					continue
				}
				w("- `%s` — %d %s `id: %s`\n", r.Selector, len(r.Policies),
					plural(len(r.Policies), "policy", "policies"), id)
			}
			w("\n")
		}

		if len(review) > 0 {
			w("### Worth a look (%d)\n\n", len(review))
			w("Nothing in these names marks them as run-to-completion, so a selector matching nothing " +
				"is either a scaled-down/powered-off workload (expected) or a genuinely dead rule " +
				"(remove it). Check before proposing anything.\n\n")
			for _, r := range review {
				id := findingID("dead-selector", r.Selector)
				if hidden(id) {
					continue
				}
				w("- `%s`%s `id: %s`\n", r.Selector, mark(id), id)
				for _, p := range r.Policies {
					w("  - `%s`\n", p)
				}
			}
			w("\n")
		}
		w("```sh\n# Does anything match this selector's labels, in any state, on any node?\n" +
			"kubectl get pods -A -l <key>=<value> --show-labels\n```\n\n")
	}

	if n == 0 {
		w("## No findings\n\nThe declared topology shows no half-open passages, no deny-coverage gaps, " +
			"no unexplained world exposure, and no dead selector references. Nothing to investigate.\n\n")
		// "Nothing found" and "nothing was looked for" read identically once
		// pasted into a chat window. Say which this is.
		if f := g.Flows; f == nil || f.Status != "ok" {
			w("Note that this run carried **no traffic observation**, so the absence of observed drops " +
				"above is not a finding — nothing was watching.\n")
		} else if f.Coverage < 0.8 {
			w("Note that only **%d%%** of the observation window was actually watched, so the "+
				"absence of observed drops above is weak evidence at best.\n", int(f.Coverage*100+0.5))
		}
	}

	// Suppressed findings are HIDDEN, never DELETED, and the brief always says
	// how many and why. A silent filter is indistinguishable from a blind spot,
	// and the day one of these decisions stops being true is the day you need to
	// be able to find it.
	if suppressed > 0 {
		w("---\n\n### Suppressed (%d)\n\n", suppressed)
		w("Withheld from the body above by an explicit decision. They are still being found — " +
			"suppression hides a finding, it does not stop looking for it. Review when the reason " +
			"stops being true.\n\n")
		for id, why := range opts.Suppressions {
			if _, live := status[id]; !live {
				continue // suppresses nothing this run; a stale entry, harmless
			}
			w("- `%s` — %s\n", id, why)
		}
		w("\n")
	}

	w("---\n\n*Generated by Portolan from declared policies. For enforcement verdicts on draft " +
		"changes, run `portolan whatif` against this snapshot. AGPL-3.0-or-later — " +
		"https://github.com/T0ut4t1s/portolan*\n")
	return []byte(b.String())
}

// ratePerHour builds a formatter that renders a raw count as a rate over the
// time actually watched, and reports whether the rate is meaningful at all.
//
// This exists because raw counts are not comparable between runs and every
// reader assumes they are. The same cluster observed at 50% coverage and at 98%
// reports counts that differ by ~2x with nothing whatsoever having changed —
// which reads as a cluster getting worse. The rate is the number that holds
// still, so it goes next to the count that does not.
//
// Below a few minutes of observation a rate is extrapolation dressed as
// measurement (one drop in 30s is not "120/h"), so it is withheld.
func ratePerHour(f *FlowOverlay) (func(int) string, bool) {
	if f == nil || f.WatchedSec < 300 {
		return func(int) string { return "" }, false
	}
	hours := f.WatchedSec / 3600
	return func(n int) string {
		r := float64(n) / hours
		switch {
		case r >= 10:
			return fmt.Sprintf(" (≈%.0f/h)", r)
		case r >= 1:
			return fmt.Sprintf(" (≈%.1f/h)", r)
		default:
			return fmt.Sprintf(" (≈%.2f/h)", r)
		}
	}, true
}

// deadRefGroup is one selector and every policy that references it.
type deadRefGroup struct {
	Selector string
	Policies []string
}

// jobLike marks names belonging to workloads that RUN AND FINISH. A selector
// matching nothing is the correct resting state for these, not a fault.
//
// This is a heuristic on names and it is allowed to be: it only decides which
// pile a finding is read in, never whether it is shown. Anything it gets wrong
// still appears, under "worth a look" — the cost of a miss is a second of
// reading, not a missed bug.
var jobLike = []string{
	"init", "job", "bootstrap", "cleanup", "populate", "post-upgrade",
	"unseal", "migrate", "schema", "sync", "startupapicheck", "onboard",
}

// groupDeadRefs turns "policy → selector" lines into one entry per SELECTOR,
// and splits off the run-to-completion ones.
//
// 54 lines became 54 findings, of which the overwhelming majority were
// `pgbouncer-db-init` — one Job, deployed into fourteen namespaces, correctly
// matching nothing because it is not running. That is one fact, and it is not
// even a problem. Burying six real questions under it is how a brief teaches
// its reader to skip the section.
func groupDeadRefs(refs []string) (expected, review []deadRefGroup) {
	idx := map[string][]string{}
	var order []string
	for _, r := range refs {
		policy, selector, ok := strings.Cut(r, " → ")
		if !ok {
			policy, selector = "", r
		}
		if _, seen := idx[selector]; !seen {
			order = append(order, selector)
		}
		idx[selector] = append(idx[selector], policy)
	}
	for _, sel := range order {
		gr := deadRefGroup{Selector: sel, Policies: idx[sel]}
		slices.Sort(gr.Policies)
		gr.Policies = slices.Compact(gr.Policies)
		// Match the selector AND the policies referencing it: the job-like word
		// often lives in the policy name (`longhorn-post-upgrade`) rather than in
		// the selector it declares.
		hay := strings.ToLower(sel + " " + strings.Join(gr.Policies, " "))
		if slices.ContainsFunc(jobLike, func(w string) bool { return strings.Contains(hay, w) }) {
			expected = append(expected, gr)
		} else {
			review = append(review, gr)
		}
	}
	return expected, review
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

// halfOpenGroup is one FACT — a policy letting a namespace out to another on
// some ports, into a default-deny that never lets it in — with the peers it
// fans across held inside it, where they belong.
type halfOpenGroup struct {
	Policies []string
	Ports    []string
	SrcNS    string
	DstNS    string
	Srcs     []string
	Dsts     []string
	// Pairs are the underlying edges, kept for the cross-reference.
	Pairs []Edge
}

// groupHalfOpen collapses per-peer half-open edges into the fact they all
// restate.
//
// A policy that names a NAMESPACE fans out to every workload in it: keycloak's
// one DNS egress rule became nine findings, one per kube-system pod, each with
// the same policy, port, diagnosis and verify recipe. Nine copies of one fact
// is not nine facts. Grouping on (policy, ports, src-ns, dst-ns) puts the fact
// in the heading and the fan-out where it belongs — in a list inside it.
func groupHalfOpen(edges []Edge) []halfOpenGroup {
	type key struct{ pols, ports, srcNS, dstNS string }
	idx := map[key]*halfOpenGroup{}
	var order []key

	for _, e := range edges {
		srcNS, _ := nodeNS(e.Src)
		dstNS, _ := nodeNS(e.Dst)
		pols := slices.Clone(e.Policies)
		slices.Sort(pols)
		ports := slices.Clone(e.Ports)
		slices.Sort(ports)

		k := key{strings.Join(pols, ","), strings.Join(ports, ","), srcNS, dstNS}
		gr, ok := idx[k]
		if !ok {
			gr = &halfOpenGroup{Policies: pols, Ports: ports, SrcNS: srcNS, DstNS: dstNS}
			idx[k] = gr
			order = append(order, k)
		}
		gr.Srcs = append(gr.Srcs, e.Src)
		gr.Dsts = append(gr.Dsts, e.Dst)
		gr.Pairs = append(gr.Pairs, e)
	}

	out := make([]halfOpenGroup, 0, len(order))
	for _, k := range order {
		gr := idx[k]
		slices.Sort(gr.Srcs)
		slices.Sort(gr.Dsts)
		gr.Srcs = slices.Compact(gr.Srcs)
		gr.Dsts = slices.Compact(gr.Dsts)
		out = append(out, *gr)
	}
	return out
}

// rankHalfOpen orders groups by EVIDENCE, not by size or name.
//
// A passage the datapath is actually denying is a fact. A passage that merely
// exists in the YAML is a hypothesis. Sorting them together — alphabetically —
// buries the first under the second, and the top of the list is the only part
// most readers reach.
func rankHalfOpen(groups []halfOpenGroup, x *crossRef) []halfOpenGroup {
	out := slices.Clone(groups)
	weight := func(gr halfOpenGroup) int {
		hit, other := x.forGroup(gr)
		switch {
		case len(other) > 0:
			return 0 // a wrong fix is sitting here waiting to be applied
		case len(hit) > 0:
			return 1 // predicted by topology, done by the datapath: real
		default:
			return 2 // declared, never exercised — probably a dead rule
		}
	}
	slices.SortFunc(out, func(p, q halfOpenGroup) int {
		return cmp.Or(
			cmp.Compare(weight(p), weight(q)),
			cmp.Compare(len(q.Dsts)+len(q.Srcs), len(p.Dsts)+len(p.Srcs)),
			cmp.Compare(p.SrcNS, q.SrcNS),
			cmp.Compare(p.DstNS, q.DstNS),
		)
	})
	return out
}

// workingSiblings finds the peers this same rule reaches SUCCESSFULLY: same
// senders, same destination namespace, overlapping ports, but with the ingress
// side declared — a complete passage, not a half-open one.
//
// This is the difference between a dead rule and a loose selector, and getting
// it wrong is dangerous.
//
// A policy whose egress rule names a NAMESPACE fans out to every workload in
// it. Keycloak's DNS egress to kube-system reaches coredns — which declares
// ingress, so it is a working passage and never appears as a half-open. What
// DOES appear are the nine other pods in kube-system that were never DNS servers
// and were never going to receive a DNS query: cilium, kube-vip, metrics-server
// and friends. They are half-open, they carry no traffic, and they never will.
//
// Report only on those and the conclusion writes itself, wrongly: "no traffic
// across 24h at 100% coverage — the rule is dead, propose removing it." Follow
// it and you delete a LIVE DNS egress rule, and Keycloak stops resolving.
//
// The tool already knows the selector is namespace-scoped — it says so, in the
// same finding. It just was not feeding that back into the conclusion. A rule
// with a working sibling is not dead. It is working, and merely too loose.
func workingSiblings(g *Graph, gr halfOpenGroup) (peers []string, carrying bool) {
	senders := map[string]bool{}
	for _, s := range gr.Srcs {
		senders[s] = true
	}
	// What actually carried traffic, so "working" can be more than a claim.
	observed := map[string]bool{}
	if g.Flows != nil && g.Flows.Status == "ok" {
		for _, o := range g.Flows.Observed {
			if o.Count > 0 {
				observed[o.Src+"|"+o.Dst] = true
			}
		}
	}

	for _, e := range g.Edges {
		if !senders[e.Src] || !e.DeclaredEgress {
			continue
		}
		dNS, ok := nodeNS(e.Dst)
		if !ok || dNS != gr.DstNS {
			continue
		}
		// The receiving side accepts: this passage is complete, not half-open.
		if !e.DeclaredIngress {
			continue
		}
		if !portsOverlap(e.Ports, gr.Ports) {
			continue
		}
		peers = append(peers, e.Dst)
		if observed[e.Src+"|"+e.Dst] {
			carrying = true
		}
	}
	slices.Sort(peers)
	return slices.Compact(peers), carrying
}

func portsOverlap(a, b []string) bool {
	for _, p := range a {
		if p == "any" || slices.Contains(b, p) || slices.Contains(b, "any") {
			return true
		}
	}
	return false
}

// forGroup is forHalfOpen over every pair a group covers.
func (x *crossRef) forGroup(gr halfOpenGroup) (hit, other []string) {
	for _, e := range gr.Pairs {
		h, o := x.forHalfOpen(e)
		hit = append(hit, h...)
		other = append(other, o...)
	}
	slices.Sort(hit)
	slices.Sort(other)
	return slices.Compact(hit), slices.Compact(other)
}

// ephemeralFrom is the low end of Linux's default ephemeral port range
// (net.ipv4.ip_local_port_range = 32768 60999). A destination port up here is
// almost never a service — it is one end of a dynamically negotiated
// connection.
const ephemeralFrom = 32768

// foldEphemeral collapses drops to dynamically-allocated ports into a single
// row per (src, dst, protocol, reason).
//
// Longhorn's instance managers are denied on a fresh high port every time —
// 37164 one run, 38906 the next, 33582 the one after. Rendered literally, the
// same standing problem looks like a brand-new finding on every brief, and
// nothing ever matches between two runs: no diff, no suppression, no memory.
// The port number carries no information; that it is ephemeral does.
func foldEphemeral(drops []DropEdge) []DropEdge {
	type key struct{ src, dst, port, reason string }
	folded := map[key]*DropEdge{}
	var order []key

	for _, d := range drops {
		k := key{d.Src, d.Dst, ephemeralLabel(d.Port), d.Reason}
		f, ok := folded[k]
		if !ok {
			c := d
			c.Port = k.port
			folded[k] = &c
			order = append(order, k)
			continue
		}
		f.Count += d.Count
		if d.LastSeen.After(f.LastSeen) {
			f.LastSeen = d.LastSeen
		}
		if !d.FirstSeen.IsZero() && (f.FirstSeen.IsZero() || d.FirstSeen.Before(f.FirstSeen)) {
			f.FirstSeen = d.FirstSeen
		}
		if d.Buckets > f.Buckets {
			f.Buckets = d.Buckets
		}
	}
	out := make([]DropEdge, 0, len(order))
	for _, k := range order {
		out = append(out, *folded[k])
	}
	return out
}

// ephemeralLabel rewrites "38906/TCP" as "ephemeral/TCP", and leaves real
// service ports alone.
func ephemeralLabel(port string) string {
	num, proto, ok := strings.Cut(port, "/")
	if !ok {
		return port
	}
	n, err := strconv.Atoi(num)
	if err != nil || n < ephemeralFrom {
		return port
	}
	return "ephemeral/" + proto
}

// rankDrops orders by consequence rather than alphabet.
//
// `cleanuparr` bleeding 57 drops an hour sat BELOW a `jellyfin` blip that
// happened once and stopped, because "c" comes before "j". The top of the list
// is the only part most readers reach, so what goes there is the whole design.
//
// Order: still happening before finished; then confirmed misconfigurations and
// port mismatches (the ones with a known, wrong, or dangerous fix) before
// unexplained ones; then loudest first.
func rankDrops(drops []DropEdge, x *crossRef, f *FlowOverlay) []DropEdge {
	out := slices.Clone(drops)
	weight := func(d DropEdge) int {
		key := d.Src + "|" + d.Dst + "|" + d.Port
		switch {
		case x.mismatch[key] != nil:
			return 0 // a wrong fix is waiting to be applied here
		case x.confirmed[key]:
			return 1 // topology predicted it and the datapath did it
		default:
			return 2
		}
	}
	live := func(d DropEdge) bool {
		if f == nil || f.BucketSec <= 0 || f.To.IsZero() {
			return true // unknown: do not demote it
		}
		return f.To.Sub(d.LastSeen) <= 2*time.Duration(f.BucketSec)*time.Second
	}
	slices.SortFunc(out, func(p, q DropEdge) int {
		if a, b := live(p), live(q); a != b {
			if a {
				return -1
			}
			return 1
		}
		return cmp.Or(
			cmp.Compare(weight(p), weight(q)),
			cmp.Compare(q.Count, p.Count), // loudest first
			cmp.Compare(p.Src, q.Src),
			cmp.Compare(p.Dst, q.Dst),
			cmp.Compare(p.Port, q.Port),
		)
	})
	return out
}

// crossRef pre-joins observed drops against half-open findings, so the reader
// does not have to — and, more importantly, so they cannot do it WRONG.
//
// The brief used to tell them: "check whether a half-open finding names the same
// pair — that pairing is a confirmed misconfiguration." That rule ignores the
// port, and on a real cluster it produced a confidently wrong fix. Longhorn's
// instance-manager was observed being denied on **38906/TCP**, while the
// half-open finding for the very same pair declares **9500/TCP**. Same source,
// same destination, different port. Follow the rule and you open 9500, the
// drops on 38906 continue, and you have added an ingress rule for nothing.
//
// A pair match is not a confirmation. A pair AND port match is. And a pair that
// matches on everything except the port is its own finding, and a louder one:
// traffic is being denied on a port no policy so much as mentions.
type crossRef struct {
	// confirmed: this drop is denied on exactly the port a half-open declares.
	// Topology predicted it and the datapath did it. Nothing is stronger.
	confirmed map[string]bool // "src|dst|port"
	// mismatch: the pair has a half-open, but on OTHER ports than the one being
	// dropped. Keyed "src|dst|port" (the dropped port), valued with the ports
	// the policy actually declares.
	mismatch map[string][]string
	// dropped: every (pair, port) actually denied, so a half-open can ask
	// whether anything was ever observed hitting it.
	dropped map[string]bool // "src|dst|port"
	// pairDropped: ports denied on a pair, for the half-open side of the join.
	pairDropped map[string][]string // "src|dst" -> ports
}

func newCrossRef(a *Audit) *crossRef {
	x := &crossRef{
		confirmed:   map[string]bool{},
		mismatch:    map[string][]string{},
		dropped:     map[string]bool{},
		pairDropped: map[string][]string{},
	}
	// What the topology declares, per pair.
	declared := map[string][]string{}
	for _, e := range a.HalfOpen {
		declared[e.Src+"|"+e.Dst] = append(declared[e.Src+"|"+e.Dst], e.Ports...)
	}
	for _, d := range a.Drops {
		pair := d.Src + "|" + d.Dst
		key := pair + "|" + d.Port
		x.dropped[key] = true
		x.pairDropped[pair] = append(x.pairDropped[pair], d.Port)

		ports, ok := declared[pair]
		if !ok {
			continue // no half-open for this pair at all
		}
		if slices.Contains(ports, d.Port) || slices.Contains(ports, "any") {
			x.confirmed[key] = true
		} else {
			x.mismatch[key] = ports
		}
	}
	return x
}

// forHalfOpen answers, for one half-open finding: which of its declared ports
// were actually seen being dropped (hit), and which OTHER ports on the same
// pair were dropped instead (other).
//
// `other` is the dangerous one. It means the finding's suggested fix does not
// address the traffic actually being denied.
func (x *crossRef) forHalfOpen(e Edge) (hit, other []string) {
	for _, p := range x.pairDropped[e.Src+"|"+e.Dst] {
		if slices.Contains(e.Ports, p) || slices.Contains(e.Ports, "any") {
			hit = append(hit, p)
		} else {
			other = append(other, p)
		}
	}
	slices.Sort(hit)
	slices.Sort(other)
	return slices.Compact(hit), slices.Compact(other)
}

// activity turns a drop's spread across time buckets into the one thing the
// reader actually needs to know: is this still happening?
//
// A count alone cannot say. 32 drops that all landed inside a single 15-minute
// bucket thirteen hours ago is a pod that had a bad start and recovered — there
// is nothing to fix, and the row is a trap. 343 drops spread across every bucket
// in the window is something bleeding right now. They used to print identically.
func activity(d DropEdge, f *FlowOverlay) string {
	if f == nil || f.BucketSec <= 0 || d.Buckets <= 0 || f.To.IsZero() {
		return "" // a buffer read has no buckets; say nothing rather than guess
	}
	age := f.To.Sub(d.LastSeen)
	if age < 0 {
		age = 0
	}
	bucket := time.Duration(f.BucketSec) * time.Second
	recent := age <= 2*bucket
	total := int(math.Ceil(f.WatchedSec / f.BucketSec))

	// Too little history to speak of a habit at all.
	//
	// This guard is load-bearing, and I only found out why by running it against
	// the cluster: with seven minutes watched and fifteen-minute buckets the
	// denominator rounded to ZERO, so "seen in every window" was trivially true
	// and a single ×1 drop got labelled "ongoing, continuously". A pattern
	// claimed from one sighting in one window is not a measurement, it is a
	// coin toss with a confident voice.
	if total < 4 {
		if recent {
			return fmt.Sprintf(" — last seen %s ago (too little history yet to say whether it recurs)", roughly(age))
		}
		return fmt.Sprintf(" — **stopped**: nothing for %s", roughly(age))
	}

	switch {
	case !recent && d.Buckets == 1:
		return fmt.Sprintf(" — **stopped**: a single burst %s ago, nothing since", roughly(age))
	case !recent:
		return fmt.Sprintf(" — **stopped** %s ago (was seen in %d of %d windows)", roughly(age), d.Buckets, total)
	case d.Buckets*10 >= total*9:
		return fmt.Sprintf(" — **ongoing**, continuously (seen in %d of %d windows)", d.Buckets, total)
	case d.Buckets == 1:
		return fmt.Sprintf(" — a single burst, %s ago — not yet a pattern", roughly(age))
	default:
		return fmt.Sprintf(" — **ongoing**, intermittently (seen in %d of %d windows)", d.Buckets, total)
	}
}

// roughly renders a duration the way someone would say it out loud.
func roughly(d time.Duration) string {
	switch {
	case d >= 24*time.Hour:
		return fmt.Sprintf("%.0fd", d.Hours()/24)
	case d >= time.Hour:
		return fmt.Sprintf("%.0fh", d.Hours())
	case d >= time.Minute:
		return fmt.Sprintf("%.0fm", d.Minutes())
	default:
		return "moments"
	}
}

// policyGetCmd turns "Kind/ns/name" or "Kind/name" provenance into a kubectl command.
func policyGetCmd(prov string) string {
	parts := strings.Split(prov, "/")
	short := map[string]string{
		"CiliumNetworkPolicy":            "cnp",
		"CiliumClusterwideNetworkPolicy": "ccnp",
		"NetworkPolicy":                  "netpol",
	}
	switch len(parts) {
	case 3:
		if s, ok := short[parts[0]]; ok {
			return fmt.Sprintf("kubectl get %s -n %s %s -o yaml", s, parts[1], parts[2])
		}
	case 2:
		if s, ok := short[parts[0]]; ok {
			return fmt.Sprintf("kubectl get %s %s -o yaml", s, parts[1])
		}
	}
	return ""
}
