// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Portolan contributors

package graph

import (
	"fmt"
	"strings"
	"time"
)

// Brief renders audit findings as a Markdown investigation brief written
// for an LLM agent (or a human) with read access to the cluster. The brief
// hands over hypotheses, evidence, and verification commands — it never
// hands over conclusions: those belong to the investigator after checking
// live state.
func Brief(g *Graph, a *Audit) []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Portolan investigation brief\n\n")
	if g.Cluster != "" {
		w("Cluster: **%s** · ", g.Cluster)
	}
	w("snapshot taken %s · generated by %s\n\n", g.TakenAt, g.Tool)
	w("Topology at capture: %d namespaces, %d workloads, %d policies, %d declared allow-edges.\n\n",
		g.Stats.Namespaces, g.Stats.Workloads, g.Stats.Policies, g.Stats.Edges)

	// Observation provenance — the most important paragraph in the brief for
	// anyone about to reason from an ABSENCE.
	//
	// "No drops on this edge" is worth almost nothing from a 2%-covered sample
	// and quite a lot from a 99%-covered one, and a reader (human or model)
	// cannot tell those apart unless we say which they are holding. A brief
	// pasted into a chatbot is exactly where that mistake gets made
	// confidently, at length, and with citations.
	if f := g.Flows; f != nil && f.Status == "ok" {
		cov := int(f.Coverage*100 + 0.5)
		w("Observed traffic: **%s** window, **%d%% covered** — %s of it actually watched (source: `%s`).\n\n",
			f.Window, cov, f.Watched, f.Source)
		switch {
		case f.Source == "buffer":
			w("> **Read this before drawing any conclusion from an absence.** These observations are a " +
				"single read of Hubble's event buffer, which is bounded by *capacity*, not time — on a busy " +
				"cluster it holds seconds no matter how long a window was asked for. Traffic missing from " +
				"this brief was almost certainly **not observed**, rather than absent. Do not conclude that " +
				"an edge is unused, and do not propose removing a rule on that basis.\n\n")
		case cov < 80:
			w("> **Read this before drawing any conclusion from an absence.** Only %d%% of this window was "+
				"actually watched, so traffic that does not appear here may simply have gone unseen. "+
				"Traffic that *is* listed is solid evidence; its absence is not.\n\n", cov)
		default:
			w("Coverage is high, so absence is meaningful here: an edge with no observed traffic in this " +
				"window genuinely carried none. That is evidence a rule may be unused — still verify before " +
				"proposing removal.\n\n")
		}
	} else if g.Flows == nil {
		w("> **No traffic observation in this brief.** Every finding below is derived from *declared " +
			"policy topology alone*. Nothing here tells you what actually flowed, so no finding can be " +
			"confirmed or dismissed from this document by itself.\n\n")
	}

	w(`## Instructions for the investigating agent

These findings come from **declared policy topology only** (visualization-grade
selector matching). They are hypotheses, not verdicts. For each finding:

1. Work **one finding at a time**. Verify against live cluster state before
   concluding anything — never diagnose from this brief alone.
2. Use **read-only commands first** (kubectl get/describe, hubble observe).
   Propose fixes as GitOps-reviewable YAML; do not apply changes directly
   unless your operator explicitly asks.
3. Classify each finding when done, with the evidence that decided it:
   - **BENIGN** — intentional or explained (completed Job, scaled-down or
     powered-off node, deliberate one-way allow, traffic that never flows)
   - **CONFIRMED** — a real gap or dead rule, with the proposed fix
   - **INCONCLUSIVE** — say exactly what evidence is missing
4. If Hubble is available, prefer flow evidence over reasoning about specs.

`)

	n := 0
	if len(a.Drops) > 0 {
		n++
		w("## Finding %d — traffic drops observed in the capture window (%d)\n\n", n, len(a.Drops))
		w("These are not topology inferences: the datapath **actually denied** this traffic "+
			"during the %s window ending %s. Strongest evidence in this brief — a drop that was "+
			"seen, happened, whatever the coverage was.\n\n",
			g.Flows.Window, g.Flows.To.Format(time.RFC3339))

		// Counts are raw totals over the time actually watched, so they scale
		// with coverage: the SAME cluster, sampled at 50% and at 98%, yields
		// counts that differ ~2x while nothing changed. That is the single most
		// misleading thing a reader can do with this section — it turns steady
		// background noise into "the cluster is degrading". So print the rate
		// beside the count, and say plainly which one to compare.
		rate, rated := ratePerHour(g.Flows)
		if rated {
			w("Counts are raw totals over the %s actually watched. To compare with another run — a "+
				"different day, a different coverage — use the **per-hour rate**, not the count: the "+
				"count scales with how long we were looking, the rate does not.\n\n", g.Flows.Watched)
		}
		for _, d := range a.Drops {
			w("- `%s → %s` %s — **%s** ×%d%s, last seen %s\n",
				d.Src, d.Dst, d.Port, d.Reason, d.Count, rate(d.Count), d.LastSeen.Format(time.RFC3339))
		}
		w("\nTriage: `POLICY_DENIED` involving two cluster workloads → almost certainly a missing " +
			"allow rule (check whether a half-open finding below names the same pair — that pairing is " +
			"a confirmed misconfiguration). `POLICY_DENIED` from `entity:world` → usually correct " +
			"enforcement doing its job; verify the exposure is intended to be closed. Other reasons " +
			"(e.g. `VLAN_FILTERED`, `CT_MAP_INSERTION_FAILED`) are datapath conditions, not policy — " +
			"investigate separately.\n\n```sh\n# Watch the pair live:\nhubble observe --verdict DROPPED " +
			"--from-namespace <src-ns> --to-namespace <dst-ns> --since 1h -o compact\n```\n\n")
	}
	for _, e := range a.HalfOpen {
		n++
		srcNS, _ := nodeNS(e.Src)
		dstNS, _ := nodeNS(e.Dst)
		w("## Finding %d — half-open passage: `%s → %s` (%s)\n\n", n, e.Src, e.Dst, strings.Join(e.Ports, ", "))
		w("**What the topology says:** egress is declared per-peer by:\n\n")
		for _, p := range e.Policies {
			w("- `%s`\n", p)
		}
		w("\n…but namespace `%s` is default-deny and **no ingress rule accepts this passage**. "+
			"If this traffic is ever sent, it is allowed out of `%s` and dropped on arrival.\n\n", dstNS, srcNS)
		w("**Verify:**\n\n```sh\n")
		w("# Does traffic actually attempt this path? Drops here confirm a real gap:\n")
		w("hubble observe --from-namespace %s --to-namespace %s --verdict DROPPED --since 1h -o compact\n", srcNS, dstNS)
		for _, p := range e.Policies {
			if cmd := policyGetCmd(p); cmd != "" {
				w("# Inspect the declaring policy:\n%s\n", cmd)
			}
		}
		w("# What does the receiver currently accept?\nkubectl get cnp,netpol -n %s -o yaml | grep -B3 -A15 ingress\n", dstNS)
		w("```\n\n**Likely outcomes:** no drops **and** the sender never targets this peer → "+
			"dead egress rule, propose removing it; drops observed → missing ingress allow on the `%s` side, "+
			"propose an ingress rule admitting `%s` on %s.\n\n", dstNS, e.Src, strings.Join(e.Ports, ", "))
	}

	if len(a.NoDefaultDeny) > 0 {
		n++
		w("## Finding %d — namespaces with workloads but no default-deny\n\n", n)
		for _, ns := range a.NoDefaultDeny {
			w("- `%s`\n", ns)
		}
		w("\nEvery workload in these namespaces is default-allow in the unpolicied direction(s). " +
			"Verify whether that is intentional; if not, propose the cluster's standard default-deny " +
			"policy for each.\n\n```sh\nkubectl get cnp,ccnp,netpol -n <namespace>\n```\n\n")
	}

	if len(a.WorldReachable) > 0 {
		n++
		w("## Finding %d — workloads with declared ingress from world/all\n\n", n)
		for _, wl := range a.WorldReachable {
			w("- `%s`\n", wl)
		}
		w("\nUsually intentional (ingress controllers, LoadBalancer services, VPN gateways). " +
			"Confirm each is a deliberate exposure path and is fronted by the expected protections; " +
			"flag anything that should not be internet-facing.\n\n")
	}

	if len(a.DeadRefs) > 0 {
		n++
		w("## Finding %d — selector references matching no live workload (%d)\n\n", n, len(a.DeadRefs))
		w("Each is `policy → selector`. Triage order: (a) selectors for Job/init pods that only " +
			"exist during runs are expected; (b) selectors for workloads on powered-off or scaled-down " +
			"nodes are expected; (c) anything left is a dead rule — verify the workload really no " +
			"longer exists, then propose removing the rule.\n\n")
		for _, r := range a.DeadRefs {
			w("- `%s`\n", r)
		}
		w("\n```sh\n# Does anything match the selector's labels (any state, any node)?\n" +
			"kubectl get pods -A -l <key>=<value> --show-labels\n```\n\n")
	}

	if n == 0 {
		w("## No findings\n\nThe declared topology shows no half-open passages, no deny-coverage gaps, " +
			"no unexplained world exposure, and no dead selector references. Nothing to investigate.\n\n")
		// "Nothing found" and "nothing was looked for" read identically once
		// pasted into a chat window. Say which this is.
		if f := g.Flows; f == nil || f.Status != "ok" {
			w("Note that this run carried **no traffic observation**, so the absence of observed drops " +
				"above is not a finding — nothing was watching.\n")
		} else if f.Coverage < 0.8 {
			w("Note that only **%d%%** of the observation window was actually watched, so the "+
				"absence of observed drops above is weak evidence at best.\n", int(f.Coverage*100+0.5))
		}
	}

	w("---\n\n*Generated by Portolan from declared policies. For enforcement verdicts on draft " +
		"changes, run `portolan whatif` against this snapshot. AGPL-3.0-or-later — " +
		"https://github.com/T0ut4t1s/portolan*\n")
	return []byte(b.String())
}

// ratePerHour builds a formatter that renders a raw count as a rate over the
// time actually watched, and reports whether the rate is meaningful at all.
//
// This exists because raw counts are not comparable between runs and every
// reader assumes they are. The same cluster observed at 50% coverage and at 98%
// reports counts that differ by ~2x with nothing whatsoever having changed —
// which reads as a cluster getting worse. The rate is the number that holds
// still, so it goes next to the count that does not.
//
// Below a few minutes of observation a rate is extrapolation dressed as
// measurement (one drop in 30s is not "120/h"), so it is withheld.
func ratePerHour(f *FlowOverlay) (func(int) string, bool) {
	if f == nil || f.WatchedSec < 300 {
		return func(int) string { return "" }, false
	}
	hours := f.WatchedSec / 3600
	return func(n int) string {
		r := float64(n) / hours
		switch {
		case r >= 10:
			return fmt.Sprintf(" (≈%.0f/h)", r)
		case r >= 1:
			return fmt.Sprintf(" (≈%.1f/h)", r)
		default:
			return fmt.Sprintf(" (≈%.2f/h)", r)
		}
	}, true
}

// policyGetCmd turns "Kind/ns/name" or "Kind/name" provenance into a kubectl command.
func policyGetCmd(prov string) string {
	parts := strings.Split(prov, "/")
	short := map[string]string{
		"CiliumNetworkPolicy":            "cnp",
		"CiliumClusterwideNetworkPolicy": "ccnp",
		"NetworkPolicy":                  "netpol",
	}
	switch len(parts) {
	case 3:
		if s, ok := short[parts[0]]; ok {
			return fmt.Sprintf("kubectl get %s -n %s %s -o yaml", s, parts[1], parts[2])
		}
	case 2:
		if s, ok := short[parts[0]]; ok {
			return fmt.Sprintf("kubectl get %s %s -o yaml", s, parts[1])
		}
	}
	return ""
}
