// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Portolan contributors

package graph

import (
	"fmt"
	"math"
	"slices"
	"strings"
	"time"
)

// Brief renders audit findings as a Markdown investigation brief written
// for an LLM agent (or a human) with read access to the cluster. The brief
// hands over hypotheses, evidence, and verification commands — it never
// hands over conclusions: those belong to the investigator after checking
// live state.
func Brief(g *Graph, a *Audit) []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	x := newCrossRef(a)

	w("# Portolan investigation brief\n\n")
	if g.Cluster != "" {
		w("Cluster: **%s** · ", g.Cluster)
	}
	w("generated by %s\n\n", g.Tool)
	w("Topology at capture: %d namespaces, %d workloads, %d policies, %d declared allow-edges.\n\n",
		g.Stats.Namespaces, g.Stats.Workloads, g.Stats.Policies, g.Stats.Edges)

	// Two clocks, said out loud.
	//
	// Policy is SAMPLED (a snapshot, every collection cycle); traffic is
	// STREAMED (continuous, and re-read the moment this brief is generated). So
	// the traffic timestamps legitimately run minutes fresher than the policy
	// one — and printing a single undated "snapshot taken" line above drops
	// last-seen AFTER it made the brief look broken. Two clocks are correct; two
	// unlabelled clocks are a bug.
	w("- **Policy** sampled at `%s` — a point-in-time read of the cluster's declared topology.\n", g.TakenAt)
	if f := g.Flows; f != nil && f.Status == "ok" && !f.To.IsZero() {
		w("- **Traffic** observed through `%s` — streamed continuously, so it runs fresher than the "+
			"policy above. Drop timestamps later than the policy sample are expected, not errors.\n",
			f.To.Format(time.RFC3339))
	}
	w("\n")

	// Observation provenance — the most important paragraph in the brief for
	// anyone about to reason from an ABSENCE.
	//
	// "No drops on this edge" is worth almost nothing from a 2%-covered sample
	// and quite a lot from a 99%-covered one, and a reader (human or model)
	// cannot tell those apart unless we say which they are holding. A brief
	// pasted into a chatbot is exactly where that mistake gets made
	// confidently, at length, and with citations.
	if f := g.Flows; f != nil && f.Status == "ok" {
		cov := int(f.Coverage*100 + 0.5)
		w("Observed traffic: **%s** window, **%d%% covered** — %s of it actually watched (source: `%s`).\n\n",
			f.Window, cov, f.Watched, f.Source)
		switch {
		case f.Source == "buffer":
			w("> **Read this before drawing any conclusion from an absence.** These observations are a " +
				"single read of Hubble's event buffer, which is bounded by *capacity*, not time — on a busy " +
				"cluster it holds seconds no matter how long a window was asked for. Traffic missing from " +
				"this brief was almost certainly **not observed**, rather than absent. Do not conclude that " +
				"an edge is unused, and do not propose removing a rule on that basis.\n\n")
		case cov < 80:
			w("> **Read this before drawing any conclusion from an absence.** Only %d%% of this window was "+
				"actually watched, so traffic that does not appear here may simply have gone unseen. "+
				"Traffic that *is* listed is solid evidence; its absence is not.\n\n", cov)
		default:
			w("Coverage is high, so absence is meaningful here: an edge with no observed traffic in this " +
				"window genuinely carried none. That is evidence a rule may be unused — still verify before " +
				"proposing removal.\n\n")
		}
	} else if g.Flows == nil {
		w("> **No traffic observation in this brief.** Every finding below is derived from *declared " +
			"policy topology alone*. Nothing here tells you what actually flowed, so no finding can be " +
			"confirmed or dismissed from this document by itself.\n\n")
	}

	w(`## Instructions for the investigating agent

These findings come from **declared policy topology only** (visualization-grade
selector matching). They are hypotheses, not verdicts. For each finding:

1. Work **one finding at a time**. Verify against live cluster state before
   concluding anything — never diagnose from this brief alone.
2. Use **read-only commands first** (kubectl get/describe, hubble observe).
   Propose fixes as GitOps-reviewable YAML; do not apply changes directly
   unless your operator explicitly asks.
3. Classify each finding when done, with the evidence that decided it:
   - **BENIGN** — intentional or explained (completed Job, scaled-down or
     powered-off node, deliberate one-way allow, traffic that never flows)
   - **CONFIRMED** — a real gap or dead rule, with the proposed fix
   - **INCONCLUSIVE** — say exactly what evidence is missing
4. If Hubble is available, prefer flow evidence over reasoning about specs.

`)

	n := 0
	if len(a.Drops) > 0 {
		n++
		w("## Finding %d — traffic drops observed in the capture window (%d)\n\n", n, len(a.Drops))
		w("These are not topology inferences: the datapath **actually denied** this traffic "+
			"during the %s window ending %s. Strongest evidence in this brief — a drop that was "+
			"seen, happened, whatever the coverage was.\n\n",
			g.Flows.Window, g.Flows.To.Format(time.RFC3339))

		// Counts are raw totals over the time actually watched, so they scale
		// with coverage: the SAME cluster, sampled at 50% and at 98%, yields
		// counts that differ ~2x while nothing changed. That is the single most
		// misleading thing a reader can do with this section — it turns steady
		// background noise into "the cluster is degrading". So print the rate
		// beside the count, and say plainly which one to compare.
		rate, rated := ratePerHour(g.Flows)
		if rated {
			w("Counts are raw totals over the %s actually watched. To compare with another run — a "+
				"different day, a different coverage — use the **per-hour rate**, not the count: the "+
				"count scales with how long we were looking, the rate does not.\n\n", g.Flows.Watched)
		}
		for _, d := range a.Drops {
			key := d.Src + "|" + d.Dst + "|" + d.Port
			var tag string
			switch {
			case x.confirmed[key]:
				tag = " · **CONFIRMED** — a half-open finding declares this exact pair and port"
			case x.mismatch[key] != nil:
				tag = " · ⚠ **PORT MISMATCH** — policy declares " +
					"`" + strings.Join(x.mismatch[key], "`, `") + "` for this pair, not this port"
			}
			w("- `%s → %s` %s — **%s** ×%d%s, last seen %s%s%s\n",
				d.Src, d.Dst, d.Port, d.Reason, d.Count, rate(d.Count),
				d.LastSeen.Format(time.RFC3339), activity(d, g.Flows), tag)
		}

		// The cross-reference, done HERE rather than asked of the reader. The
		// old instruction — "a half-open naming the same pair confirms it" —
		// ignores the port, and on this cluster that produced a fix that would
		// not have worked. See crossRef.
		if len(x.mismatch) > 0 {
			w("\n### ⚠ Denied on a port no policy declares\n\n")
			w("The pairs below are being denied on a port that **none of their policies mention**. " +
				"Each also has a half-open finding further down, on a DIFFERENT port — so the obvious " +
				"move, opening the port the policy names, would leave these drops exactly where they " +
				"are. Do not follow that half-open's suggested fix for this traffic. Establish what is " +
				"really talking on the dropped port first; a dynamic or ephemeral port usually means " +
				"the policy is written against the wrong port in the first place.\n\n")
			for _, d := range a.Drops {
				ports, ok := x.mismatch[d.Src+"|"+d.Dst+"|"+d.Port]
				if !ok {
					continue
				}
				w("- `%s → %s` — **denied on %s**, but policy only declares %s\n",
					d.Src, d.Dst, d.Port, "`"+strings.Join(ports, "`, `")+"`")
			}
			w("\n")
		}

		w("\nTriage:\n\n" +
			"- **`POLICY_DENIED` between two cluster workloads, on a port a half-open finding also " +
			"declares** → confirmed misconfiguration. Topology predicted it and the datapath did it; " +
			"nothing in this brief is stronger. Those drops are marked below.\n" +
			"- **`POLICY_DENIED` on a port no policy declares** → see the section above. The pair " +
			"matching is NOT enough; the port has to match too.\n" +
			"- **`POLICY_DENIED` to or from `entity:world`** → usually correct enforcement doing its " +
			"job. Verify the exposure is meant to be closed rather than rushing to open it.\n" +
			"- **Other reasons** (`VLAN_FILTERED`, `CT_MAP_INSERTION_FAILED`) are datapath conditions, " +
			"not policy — investigate separately.\n" +
			"- **A drop marked `stopped`** already ended. Do not open a rule for traffic that is no " +
			"longer being attempted; find out what changed instead.\n" +
			"\n```sh\n# Watch the pair live:\nhubble observe --verdict DROPPED " +
			"--from-namespace <src-ns> --to-namespace <dst-ns> --since 1h -o compact\n```\n\n")
	}
	for _, e := range a.HalfOpen {
		n++
		srcNS, _ := nodeNS(e.Src)
		dstNS, _ := nodeNS(e.Dst)
		w("## Finding %d — half-open passage: `%s → %s` (%s)\n\n", n, e.Src, e.Dst, strings.Join(e.Ports, ", "))
		w("**What the topology says:** egress is declared per-peer by:\n\n")
		for _, p := range e.Policies {
			w("- `%s`\n", p)
		}
		w("\n…but namespace `%s` is default-deny and **no ingress rule accepts this passage**. "+
			"If this traffic is ever sent, it is allowed out of `%s` and dropped on arrival.\n\n", dstNS, srcNS)

		// What was ACTUALLY denied on this pair, cross-referenced by port. The
		// three answers demand three different responses, and the brief used to
		// give the same one to all three.
		hit, other := x.forHalfOpen(e)
		switch {
		case len(hit) > 0:
			w("**Observed:** this passage is genuinely being denied — `%s` dropped on `%s`. "+
				"Topology predicted it and the datapath did it. This one is real.\n\n",
				e.Dst, strings.Join(hit, "`, `"))
		case len(other) > 0:
			w("**⚠ Observed, but NOT on this port.** Traffic to `%s` is being denied on `%s` — not on "+
				"`%s`, which is what this policy declares. **Do not apply the fix suggested below to "+
				"that traffic**: opening `%s` would leave those drops untouched. Two separate things are "+
				"happening on this pair, and only one of them is the finding you are reading. Work out "+
				"what is really talking on `%s` first — a dynamic or ephemeral port usually means the "+
				"policy names the wrong port.\n\n",
				e.Dst, strings.Join(other, "`, `"), strings.Join(e.Ports, "`, `"),
				strings.Join(e.Ports, "`, `"), strings.Join(other, "`, `"))
		case g.Flows != nil && g.Flows.Status == "ok" && g.Flows.Coverage >= 0.8:
			w("**Observed:** nothing. Across %s of watched traffic (%.0f%% coverage) this passage was "+
				"never attempted — no drops, no flows. At this coverage that is real evidence the rule "+
				"is dead rather than broken. Verify, then propose removing it.\n\n",
				g.Flows.Watched, g.Flows.Coverage*100)
		}

		w("**Verify:**\n\n```sh\n")
		w("# Does traffic actually attempt this path? Drops here confirm a real gap:\n")
		w("hubble observe --from-namespace %s --to-namespace %s --verdict DROPPED --since 1h -o compact\n", srcNS, dstNS)
		for _, p := range e.Policies {
			if cmd := policyGetCmd(p); cmd != "" {
				w("# Inspect the declaring policy:\n%s\n", cmd)
			}
		}
		w("# What does the receiver currently accept?\nkubectl get cnp,netpol -n %s -o yaml | grep -B3 -A15 ingress\n", dstNS)
		w("```\n\n**Likely outcomes:** no drops **and** the sender never targets this peer → "+
			"dead egress rule, propose removing it; drops observed **on these ports** → missing ingress "+
			"allow on the `%s` side, propose an ingress rule admitting `%s` on %s. Drops on any OTHER "+
			"port are a different problem and this fix will not touch them.\n\n",
			dstNS, e.Src, strings.Join(e.Ports, ", "))
	}

	if len(a.NoDefaultDeny) > 0 {
		n++
		w("## Finding %d — namespaces with workloads but no default-deny\n\n", n)
		for _, ns := range a.NoDefaultDeny {
			w("- `%s`\n", ns)
		}
		w("\nEvery workload in these namespaces is default-allow in the unpolicied direction(s). " +
			"Verify whether that is intentional; if not, propose the cluster's standard default-deny " +
			"policy for each.\n\n```sh\nkubectl get cnp,ccnp,netpol -n <namespace>\n```\n\n")
	}

	if len(a.WorldReachable) > 0 {
		n++
		w("## Finding %d — workloads with declared ingress from world/all\n\n", n)
		for _, wl := range a.WorldReachable {
			w("- `%s`\n", wl)
		}
		w("\nUsually intentional (ingress controllers, LoadBalancer services, VPN gateways). " +
			"Confirm each is a deliberate exposure path and is fronted by the expected protections; " +
			"flag anything that should not be internet-facing.\n\n")
	}

	if len(a.DeadRefs) > 0 {
		n++
		w("## Finding %d — selector references matching no live workload (%d)\n\n", n, len(a.DeadRefs))
		w("Each is `policy → selector`. Triage order: (a) selectors for Job/init pods that only " +
			"exist during runs are expected; (b) selectors for workloads on powered-off or scaled-down " +
			"nodes are expected; (c) anything left is a dead rule — verify the workload really no " +
			"longer exists, then propose removing the rule.\n\n")
		for _, r := range a.DeadRefs {
			w("- `%s`\n", r)
		}
		w("\n```sh\n# Does anything match the selector's labels (any state, any node)?\n" +
			"kubectl get pods -A -l <key>=<value> --show-labels\n```\n\n")
	}

	if n == 0 {
		w("## No findings\n\nThe declared topology shows no half-open passages, no deny-coverage gaps, " +
			"no unexplained world exposure, and no dead selector references. Nothing to investigate.\n\n")
		// "Nothing found" and "nothing was looked for" read identically once
		// pasted into a chat window. Say which this is.
		if f := g.Flows; f == nil || f.Status != "ok" {
			w("Note that this run carried **no traffic observation**, so the absence of observed drops " +
				"above is not a finding — nothing was watching.\n")
		} else if f.Coverage < 0.8 {
			w("Note that only **%d%%** of the observation window was actually watched, so the "+
				"absence of observed drops above is weak evidence at best.\n", int(f.Coverage*100+0.5))
		}
	}

	w("---\n\n*Generated by Portolan from declared policies. For enforcement verdicts on draft " +
		"changes, run `portolan whatif` against this snapshot. AGPL-3.0-or-later — " +
		"https://github.com/T0ut4t1s/portolan*\n")
	return []byte(b.String())
}

// ratePerHour builds a formatter that renders a raw count as a rate over the
// time actually watched, and reports whether the rate is meaningful at all.
//
// This exists because raw counts are not comparable between runs and every
// reader assumes they are. The same cluster observed at 50% coverage and at 98%
// reports counts that differ by ~2x with nothing whatsoever having changed —
// which reads as a cluster getting worse. The rate is the number that holds
// still, so it goes next to the count that does not.
//
// Below a few minutes of observation a rate is extrapolation dressed as
// measurement (one drop in 30s is not "120/h"), so it is withheld.
func ratePerHour(f *FlowOverlay) (func(int) string, bool) {
	if f == nil || f.WatchedSec < 300 {
		return func(int) string { return "" }, false
	}
	hours := f.WatchedSec / 3600
	return func(n int) string {
		r := float64(n) / hours
		switch {
		case r >= 10:
			return fmt.Sprintf(" (≈%.0f/h)", r)
		case r >= 1:
			return fmt.Sprintf(" (≈%.1f/h)", r)
		default:
			return fmt.Sprintf(" (≈%.2f/h)", r)
		}
	}, true
}

// crossRef pre-joins observed drops against half-open findings, so the reader
// does not have to — and, more importantly, so they cannot do it WRONG.
//
// The brief used to tell them: "check whether a half-open finding names the same
// pair — that pairing is a confirmed misconfiguration." That rule ignores the
// port, and on a real cluster it produced a confidently wrong fix. Longhorn's
// instance-manager was observed being denied on **38906/TCP**, while the
// half-open finding for the very same pair declares **9500/TCP**. Same source,
// same destination, different port. Follow the rule and you open 9500, the
// drops on 38906 continue, and you have added an ingress rule for nothing.
//
// A pair match is not a confirmation. A pair AND port match is. And a pair that
// matches on everything except the port is its own finding, and a louder one:
// traffic is being denied on a port no policy so much as mentions.
type crossRef struct {
	// confirmed: this drop is denied on exactly the port a half-open declares.
	// Topology predicted it and the datapath did it. Nothing is stronger.
	confirmed map[string]bool // "src|dst|port"
	// mismatch: the pair has a half-open, but on OTHER ports than the one being
	// dropped. Keyed "src|dst|port" (the dropped port), valued with the ports
	// the policy actually declares.
	mismatch map[string][]string
	// dropped: every (pair, port) actually denied, so a half-open can ask
	// whether anything was ever observed hitting it.
	dropped map[string]bool // "src|dst|port"
	// pairDropped: ports denied on a pair, for the half-open side of the join.
	pairDropped map[string][]string // "src|dst" -> ports
}

func newCrossRef(a *Audit) *crossRef {
	x := &crossRef{
		confirmed:   map[string]bool{},
		mismatch:    map[string][]string{},
		dropped:     map[string]bool{},
		pairDropped: map[string][]string{},
	}
	// What the topology declares, per pair.
	declared := map[string][]string{}
	for _, e := range a.HalfOpen {
		declared[e.Src+"|"+e.Dst] = append(declared[e.Src+"|"+e.Dst], e.Ports...)
	}
	for _, d := range a.Drops {
		pair := d.Src + "|" + d.Dst
		key := pair + "|" + d.Port
		x.dropped[key] = true
		x.pairDropped[pair] = append(x.pairDropped[pair], d.Port)

		ports, ok := declared[pair]
		if !ok {
			continue // no half-open for this pair at all
		}
		if slices.Contains(ports, d.Port) || slices.Contains(ports, "any") {
			x.confirmed[key] = true
		} else {
			x.mismatch[key] = ports
		}
	}
	return x
}

// forHalfOpen answers, for one half-open finding: which of its declared ports
// were actually seen being dropped (hit), and which OTHER ports on the same
// pair were dropped instead (other).
//
// `other` is the dangerous one. It means the finding's suggested fix does not
// address the traffic actually being denied.
func (x *crossRef) forHalfOpen(e Edge) (hit, other []string) {
	for _, p := range x.pairDropped[e.Src+"|"+e.Dst] {
		if slices.Contains(e.Ports, p) || slices.Contains(e.Ports, "any") {
			hit = append(hit, p)
		} else {
			other = append(other, p)
		}
	}
	slices.Sort(hit)
	slices.Sort(other)
	return slices.Compact(hit), slices.Compact(other)
}

// activity turns a drop's spread across time buckets into the one thing the
// reader actually needs to know: is this still happening?
//
// A count alone cannot say. 32 drops that all landed inside a single 15-minute
// bucket thirteen hours ago is a pod that had a bad start and recovered — there
// is nothing to fix, and the row is a trap. 343 drops spread across every bucket
// in the window is something bleeding right now. They used to print identically.
func activity(d DropEdge, f *FlowOverlay) string {
	if f == nil || f.BucketSec <= 0 || d.Buckets <= 0 || f.To.IsZero() {
		return "" // a buffer read has no buckets; say nothing rather than guess
	}
	age := f.To.Sub(d.LastSeen)
	if age < 0 {
		age = 0
	}
	bucket := time.Duration(f.BucketSec) * time.Second
	recent := age <= 2*bucket
	total := int(math.Ceil(f.WatchedSec / f.BucketSec))

	// Too little history to speak of a habit at all.
	//
	// This guard is load-bearing, and I only found out why by running it against
	// the cluster: with seven minutes watched and fifteen-minute buckets the
	// denominator rounded to ZERO, so "seen in every window" was trivially true
	// and a single ×1 drop got labelled "ongoing, continuously". A pattern
	// claimed from one sighting in one window is not a measurement, it is a
	// coin toss with a confident voice.
	if total < 4 {
		if recent {
			return fmt.Sprintf(" — last seen %s ago (too little history yet to say whether it recurs)", roughly(age))
		}
		return fmt.Sprintf(" — **stopped**: nothing for %s", roughly(age))
	}

	switch {
	case !recent && d.Buckets == 1:
		return fmt.Sprintf(" — **stopped**: a single burst %s ago, nothing since", roughly(age))
	case !recent:
		return fmt.Sprintf(" — **stopped** %s ago (was seen in %d of %d windows)", roughly(age), d.Buckets, total)
	case d.Buckets*10 >= total*9:
		return fmt.Sprintf(" — **ongoing**, continuously (seen in %d of %d windows)", d.Buckets, total)
	case d.Buckets == 1:
		return fmt.Sprintf(" — a single burst, %s ago — not yet a pattern", roughly(age))
	default:
		return fmt.Sprintf(" — **ongoing**, intermittently (seen in %d of %d windows)", d.Buckets, total)
	}
}

// roughly renders a duration the way someone would say it out loud.
func roughly(d time.Duration) string {
	switch {
	case d >= 24*time.Hour:
		return fmt.Sprintf("%.0fd", d.Hours()/24)
	case d >= time.Hour:
		return fmt.Sprintf("%.0fh", d.Hours())
	case d >= time.Minute:
		return fmt.Sprintf("%.0fm", d.Minutes())
	default:
		return "moments"
	}
}

// policyGetCmd turns "Kind/ns/name" or "Kind/name" provenance into a kubectl command.
func policyGetCmd(prov string) string {
	parts := strings.Split(prov, "/")
	short := map[string]string{
		"CiliumNetworkPolicy":            "cnp",
		"CiliumClusterwideNetworkPolicy": "ccnp",
		"NetworkPolicy":                  "netpol",
	}
	switch len(parts) {
	case 3:
		if s, ok := short[parts[0]]; ok {
			return fmt.Sprintf("kubectl get %s -n %s %s -o yaml", s, parts[1], parts[2])
		}
	case 2:
		if s, ok := short[parts[0]]; ok {
			return fmt.Sprintf("kubectl get %s %s -o yaml", s, parts[1])
		}
	}
	return ""
}
